import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Impact from "@/components/Impact";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Education from "@/components/Education";
import Visit from "@/components/Visit";
import Cards from "@/components/Cards";
import News from "@/components/News";
import Calendar from "@/components/Calendar";
import Amsterdam from "@/components/Amsterdam";
import Look from "@/components/Look";
import Features from "@/components/Features";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Vrije Univeristie Amsterdam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-roboto font-light bg-gray1">
        <Navbar/>
        <Hero/>
        <Education/>
        <Visit left="Do you also want to change your world?" right={`Visit the VU Master’s Event`}/>
        <Impact/>
        <Cards />
        <News/>
        <Calendar />
        <Visit left="Working at VU Amsterdam?" right={`Take a look at our vacancies!`}/>
        <Amsterdam/>
        <Look />
        <Features />
        <Footer/>
      </main>
    </>
  );
}
